### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by pjastr** [wcaleniepodejrzanerepo/zbior_krzaczkowski#1]
https://github.com/wcaleniepodejrzanerepo/zbior_krzaczkowski/blob/d305259791b40e50fa7e28e8421d21ae460c2837/Zestaw22_PS_K2_2021/zadanie4/main.c#L27

W tym zadaniu w main wypada stworzyć strukturę (zmienną strukturalną), a nie tylko ustawiać jej pola. Trochę za szybko.

**Comment by wcaleniepodejrzanerepo** [comment]
Chodzi o coś takiego?

```c
int main()
{
    struct Ksiazka tab[2] = {
        {"Harry Potter", 2001, 5.9},
        {"Hobbit", 2005, 4.5}
    };

    printf("%s %d ocena: %.2f\n",tab[0].tytul,tab[0].rok, tab[0].ocena);
    printf("%d\n",dlugosc(2,tab));

    return 0;
}

```

**Comment by pjastr** [comment]
Tak, zgadza się.
